<header id="rosHeader" class="">
    <nav id="rosNav" class=""> 
        <div id="navHead" class="">
            <?php get_template_part('templates/nav','head'); ?>    
        </div><!-- /# navHead-->   
        <div id="navBody" class="">
            <?php get_template_part('templates/nav','body'); ?>    
        </div><!-- /#navBody -->   
    </nav><!-- /#rosNav -->
</header><!-- /#rosHeader -->